[package]
name = "voraus-ros-bridge"
version = "0.1.0"
edition = "2021"

[[bin]]
name="simple_publisher"
path="src/simple_publisher.rs"

[[bin]]
name="simple_subscriber"
path="src/simple_subscriber.rs"

[dependencies]
rclrs = "0.4.1"
std_msgs = "4.2.4"