services:
    voraus_ros_bridge:
        image: ghcr.io/vorausrobotik/voraus-ros-bridge:main
        command: ros2 launch voraus-ros-bridge voraus-ros-bridge.launch.py
        network_mode: host
        stop_signal: SIGINT
        environment:
            - AMENT_PREFIX_PATH=/root/voraus-ros-bridge/install/voraus-ros-bridge:/opt/ros/humble
            - ROS_NAMESPACE=robot1
            - VORAUS_CORE_OPC_UA_ENDPOINT=opc.tcp://127.0.0.1:48401
