services:
    voraus_ros_bridge:
        image: voraus-ros-bridge:0.1.0
        command: ros2 launch voraus-ros-bridge voraus-ros-bridge.launch.py
        environment:
            - AMENT_PREFIX_PATH=/root/voraus-ros-bridge/install/voraus-ros-bridge:/opt/ros/humble
            - ROS_NAMESPACE=robot1
