#!/bin/bash

echo "Building voraus_interfaces with colcon"
. /opt/ros/humble/setup.bash && . ~/ros_deps/install/setup.bash && cd ~/workspace/voraus_interfaces && colcon build
echo "source ~/workspace/voraus_interfaces/install/setup.bash" >> ~/.bashrc

echo "Building workspace with colcon"
. /opt/ros/humble/setup.bash && . ~/ros_deps/install/setup.bash && . ~/workspace/voraus_interfaces/install/setup.bash && cd ~/workspace && colcon build
echo "source ~/workspace/install/setup.bash" >> ~/.bashrc

# Run the CMD (either the default from the Dockerfile or the one provided as docker run argument)
exec "$@"
