name: CI
'on':
  push:
    branches:
      - main
  pull_request: null
env:
  CARGO_TERM_COLOR: always
jobs:
  format_code:
    uses: ./.github/workflows/ci_format_code.yml
  build_dev_container:
    uses: ./.github/workflows/ci_build_dev_container.yml
  build:
    needs: build_dev_container
    uses: ./.github/workflows/ci_build.yml
  unit_test:
    needs: build_dev_container
    uses: ./.github/workflows/ci_unit_test.yml
  integration_test:
    needs: build_dev_container
    uses: ./.github/workflows/ci_integration_test.yml
  lint:
    needs: build_dev_container
    uses: ./.github/workflows/ci_lint.yml
