name: CI
'on':
  push:
    branches:
      - main
  pull_request: null
env:
  CARGO_TERM_COLOR: always
jobs:
  format_code:
    uses: ./.github/workflows/ci_format_code.yml
  lint:
    uses: ./.github/workflows/ci_lint.yml
  test:
    uses: ./.github/workflows/ci_test.yml
