name: CI
'on':
  push:
    branches:
      - main
  pull_request: null
env:
  CARGO_TERM_COLOR: always
jobs:
  format_code:
    uses: ./.github/workflows/ci_format_code.yml
  build_dev_container:
    uses: ./.github/workflows/ci_build_dev_container.yml
  launch_dev_container:
    needs: build_dev_container
    uses: ./.github/workflows/ci_launch_dev_container.yml
  build:
    needs: launch_dev_container
    uses: ./.github/workflows/ci_build.yml
  test:
    needs: launch_dev_container
    uses: ./.github/workflows/ci_test.yml
  lint:
    needs: launch_dev_container
    uses: ./.github/workflows/ci_lint.yml
