name: CI build dev container
'on':
  workflow_call: null
jobs:
  build_dev_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/vorausrobotik/voraus-ros-bridge-dev
          cacheFrom: ghcr.io/vorausrobotik/voraus-ros-bridge-dev
          push: filter
          refFilterForPush: refs/heads/main
