name: CI launch dev container
'on':
  workflow_call: null
jobs:
  build_dev_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build workspace by executing the container entrypoint
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/vorausrobotik/voraus-ros-bridge-dev
          runCmd: echo entrypoint execution finished
          push: never
