name: CI Unit Test
'on':
  workflow_call: null
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cargo unit tests
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/vorausrobotik/voraus-ros-bridge-dev
          runCmd: cargo test --bins --verbose
          push: never
